a8snowflake:
  outputs:
    dev:
      account: "{{ env_var('ACCOUNT') }}"
      user: "{{ env_var('SF_USERNAME') }}"
      password: "{{ env_var('SF_PASSWORD') }}"
      database: "{{ env_var('DATABASE') }}"
      schema: "{{ env_var('SCHEMA') }}"
      role: "{{ env_var('ROLE') }}"
      warehouse: "{{ env_var('WAREHOUSE') }}"
      threads: 4
      type: snowflake
  target: dev

